### ISSUE TITLE
Kopia på zippaket

### ISSUE THREAD

**Issue by magnuswenzerSMHI** [nodc-sweden/sharkadm-zip-publisher#22]
- [x] Skapa kopia till SHARKzip på de zip-paket som publiceras 
- [x] Rensa bort gammalt paket om nytt datum kommer in

**Comment by magnuswenzerSMHI** [comment]
@mikaelhedblom Punkt två bör gälla, eller hur?

**Comment by mikaelhedblom** [comment]
japp precis gamla versioner skall ej sparas

**Comment by magnuswenzerSMHI** [comment]
@mikaelhedblom Hur gör vi med borttagning. Ska det göras i "vår" map också då?

**Comment by mikaelhedblom** [comment]
rör inte SHARKdata_datasets

du uppdaterar till senaste version i SHARKzip
