### ISSUE TITLE
Hantera ofullständig datum

### ISSUE THREAD

**Issue by magnuswenzerSMHI** [nodc-sweden/sharkadm-zip-publisher#23]
- [x] Ny kolumn: reported_visit_date
- [x] Ny kolumn: reported_sample_date
- [x] Ny kolumn: shark_comment 
- [x] Kopiera visit_date till reported_visit_date
- [x] Kopiera sample_date till reported_sample_date
- [x] Skapa fullständigt visit_date
- [x] Skapa fullständigt sample_date

**Comment by magnuswenzerSMHI** [comment]
@mikaelhedblom Vilka datum ska vi välja: 
Endast år: Första januari 
Endast år och månad: första i månaden 
Mitten på månad?

**Comment by mikaelhedblom** [comment]
första i månaden, så blir det likadant som i prod nu
